[v1]
"alacritty 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["alacritty"]
"cargo-aoc 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-aoc"]
"cargo-audit 0.17.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-binstall 0.23.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
"cargo-binutils 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-cov",
    "cargo-nm",
    "cargo-objcopy",
    "cargo-objdump",
    "cargo-profdata",
    "cargo-readobj",
    "cargo-size",
    "cargo-strip",
    "rust-ar",
    "rust-cov",
    "rust-ld",
    "rust-lld",
    "rust-nm",
    "rust-objcopy",
    "rust-objdump",
    "rust-profdata",
    "rust-readobj",
    "rust-size",
    "rust-strip",
]
"cargo-bloat 0.11.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-bundle 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bundle"]
"cargo-cache 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cache"]
"cargo-chef 0.1.61 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-chef"]
"cargo-deps-list 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deps-list"]
"cargo-edit 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-generate 0.18.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-generate"]
"cargo-i18n 0.2.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-i18n"]
"cargo-llvm-cov 0.5.20 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-llvm-cov"]
"cargo-nextest 0.9.53 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"cargo-public-api 0.31.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-public-api"]
"cargo-release 0.24.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-release"]
"cargo-show-asm 0.2.18 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-asm"]
"cargo-udeps 0.1.40 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-udeps"]
"cargo-update 13.0.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-vet 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-vet"]
"cargo-workspaces 0.2.43 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-workspaces",
    "cargo-ws",
]
"codemov 0.1.0 (git+https://github.com/sloganking/codemov.git#ab4b287c5cdb64f8a1f378c54070fde5a1f3be5b)" = ["codemov"]
"codevis 0.8.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["codevis"]
"diesel_cli 2.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["diesel"]
"fj-app 0.46.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["fj-app"]
"git-ai-commit 0.1.0 (path+file:///home/milomoisson/projects/git-ai-commit)" = ["git-ai-commit"]
"git-cliff 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "git-cliff",
    "git-cliff-completions",
    "git-cliff-mangen",
]
"git-leave 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-leave"]
"gpg-tui 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "gpg-tui",
    "gpg-tui-completions",
]
"gping 1.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["gping"]
"grc 1.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["grc"]
"pgpaste-cli 0.0.0 (path+file:///home/milomoisson/Documents/Developement/Personal/pgpaste/pgpaste-cli)" = ["pgpaste"]
"probe-rs-debugger 0.18.0 (git+https://github.com/probe-rs/probe-rs?branch=master#3ea724de5db6d54050732768e6e3cbb30b3221b7)" = ["probe-rs-debugger"]
"probe-run 0.3.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["probe-run"]
"qrscan 0.1.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["qrscan"]
"runst 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["runst"]
"rustfilt 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustfilt"]
"sequoia-sq 0.30.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["sq"]
"sfz 0.7.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["sfz"]
"sozu 0.14.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["sozu"]
"spacedisplay 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["spacedisplay"]
"swp 1.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["swp"]
"tealdeer 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"termimage 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["termimage"]
"thokr 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["thokr"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"tokio-console 0.1.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokio-console"]
"topgrade 11.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["topgrade"]
"wasm-pack 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-pack"]
"trunk 0.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
"leptosfmt 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["leptosfmt"]
"cargo-leptos 0.1.11 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-leptos"]
"cargo-expand 1.0.54 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-semver-checks 0.22.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-semver-checks"]
