[v1]
"agree 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["agree"]
"alacritty 0.12.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["alacritty"]
"cargo-aoc 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-aoc"]
"cargo-audit 0.18.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-binstall 1.4.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
"cargo-binutils 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-cov",
    "cargo-nm",
    "cargo-objcopy",
    "cargo-objdump",
    "cargo-profdata",
    "cargo-readobj",
    "cargo-size",
    "cargo-strip",
    "rust-ar",
    "rust-cov",
    "rust-ld",
    "rust-lld",
    "rust-nm",
    "rust-objcopy",
    "rust-objdump",
    "rust-profdata",
    "rust-readobj",
    "rust-size",
    "rust-strip",
]
"cargo-bloat 0.11.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-bundle 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bundle"]
"cargo-cache 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cache"]
"cargo-chef 0.1.62 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-chef"]
"cargo-deps-list 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deps-list"]
"cargo-edit 0.12.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-expand 1.0.74 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-feature 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-feature"]
"cargo-generate 0.18.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-generate"]
"cargo-i18n 0.2.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-i18n"]
"cargo-insta 1.34.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-insta"]
"cargo-leptos 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-leptos"]
"cargo-llvm-cov 0.5.35 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-llvm-cov"]
"cargo-nextest 0.9.59 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"cargo-public-api 0.32.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-public-api"]
"cargo-release 0.24.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-release"]
"cargo-semver-checks 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-semver-checks"]
"cargo-show-asm 0.2.21 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-asm"]
"cargo-tarpaulin 0.27.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tarpaulin"]
"cargo-udeps 0.1.43 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-udeps"]
"cargo-update 13.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-vet 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-vet"]
"cargo-workspaces 0.2.44 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-workspaces",
    "cargo-ws",
]
"codevis 0.8.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["codevis"]
"diesel_cli 2.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["diesel"]
"dysk 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["dysk"]
"flamegraph 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-flamegraph",
    "flamegraph",
]
"git-ai-commit 0.1.0 (path+file:///home/milomoisson/projects/git-ai-commit)" = ["git-ai-commit"]
"git-cliff 1.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "git-cliff",
    "git-cliff-completions",
    "git-cliff-mangen",
]
"git-leave 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-leave"]
"gpg-tui 0.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "gpg-tui",
    "gpg-tui-completions",
]
"gping 1.14.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["gping"]
"grass 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["grass"]
"grc 1.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["grc"]
"grcov 0.8.19 (registry+https://github.com/rust-lang/crates.io-index)" = ["grcov"]
"joshuto 0.9.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["joshuto"]
"neovide 0.11.2 (git+https://github.com/neovide/neovide#85234dc3e69a7b3ecbbe13ba63f7f384a481f013)" = ["neovide"]
"panamax 1.0.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["panamax"]
"pgpaste-cli 0.0.0 (path+file:///home/milomoisson/Documents/Developement/Personal/pgpaste/pgpaste-cli)" = ["pgpaste"]
"probe-run 0.3.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["probe-run"]
"qrscan 0.1.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["qrscan"]
"runst 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["runst"]
"rustfilt 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustfilt"]
"samply 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["samply"]
"sequoia-sq 0.31.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sq"]
"sfz 0.7.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["sfz"]
"songrec 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["songrec"]
"spacedisplay 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["spacedisplay"]
"subconv 0.1.0 (path+file:///home/milomoisson/Documents/Developement/Personal/subconv)" = ["subconv"]
"sudo-rs 0.2.0 (path+file:///home/milomoisson/Documents/Developement/OSS/sudo-rs)" = [
    "su",
    "sudo",
    "visudo",
]
"swp 1.0.3 (path+file:///home/milomoisson/Documents/Developement/OSS/sweep)" = ["swp"]
"tealdeer 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"termimage 1.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["termimage"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"tokio-console 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokio-console"]
"topgrade 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["topgrade"]
"trunk 0.17.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
"twiggy 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["twiggy"]
"wasm-bindgen-cli 0.2.87 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "wasm-bindgen",
    "wasm-bindgen-test-runner",
    "wasm2es6js",
]
"wasm-pack 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-pack"]
"yarer 0.1.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["yarer"]
