[v1]
"cargo-aoc 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-aoc"]
"cargo-binstall 0.19.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
"cargo-binutils 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-cov",
    "cargo-nm",
    "cargo-objcopy",
    "cargo-objdump",
    "cargo-profdata",
    "cargo-readobj",
    "cargo-size",
    "cargo-strip",
    "rust-ar",
    "rust-cov",
    "rust-ld",
    "rust-lld",
    "rust-nm",
    "rust-objcopy",
    "rust-objdump",
    "rust-profdata",
    "rust-readobj",
    "rust-size",
    "rust-strip",
]
"cargo-bundle 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bundle"]
"cargo-deps-list 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deps-list"]
"cargo-edit 0.11.8 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-expand 1.0.40 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-generate 0.17.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-generate"]
"cargo-nextest 0.9.49 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"cargo-release 0.24.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-release"]
"cargo-semver-checks 0.17.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-semver-checks"]
"cargo-show-asm 0.2.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-asm"]
"cargo-udeps 0.1.35 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-udeps"]
"cargo-update 11.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-update 11.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-update 11.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-workspaces 0.2.35 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-workspaces",
    "cargo-ws",
]
"codevis 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["codevis"]
"diesel_cli 2.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["diesel"]
"fj-app 0.34.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fj-app"]
"git-cliff 1.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "git-cliff",
    "git-cliff-completions",
    "git-cliff-mangen",
]
"git-leave 1.5.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-leave"]
"gping 1.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["gping"]
"grc 1.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["grc"]
"probe-rs-debugger 0.16.0 (git+https://github.com/probe-rs/probe-rs?branch=master#ab03d7445b551354dbe6d913882759e4c07a87f2)" = ["probe-rs-debugger"]
"probe-run 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["probe-run"]
"rustfilt 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustfilt"]
"swp 1.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["swp"]
"tealdeer 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"termimage 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["termimage"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"tokio-console 0.1.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokio-console"]
"topgrade 10.2.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["topgrade"]
"wasm-pack 0.10.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-pack"]
