[v1]
"alacritty 0.12.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["alacritty"]
"cargo-aoc 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-aoc"]
"cargo-audit 0.17.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-binstall 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
"cargo-binutils 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-cov",
    "cargo-nm",
    "cargo-objcopy",
    "cargo-objdump",
    "cargo-profdata",
    "cargo-readobj",
    "cargo-size",
    "cargo-strip",
    "rust-ar",
    "rust-cov",
    "rust-ld",
    "rust-lld",
    "rust-nm",
    "rust-objcopy",
    "rust-objdump",
    "rust-profdata",
    "rust-readobj",
    "rust-size",
    "rust-strip",
]
"cargo-bloat 0.11.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-bundle 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bundle"]
"cargo-cache 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cache"]
"cargo-chef 0.1.61 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-chef"]
"cargo-deps-list 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deps-list"]
"cargo-edit 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-expand 1.0.59 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-generate 0.18.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-generate"]
"cargo-i18n 0.2.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-i18n"]
"cargo-leptos 0.1.11 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-leptos"]
"cargo-nextest 0.9.54 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"cargo-public-api 0.31.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-public-api"]
"cargo-release 0.24.11 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-release"]
"cargo-semver-checks 0.22.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-semver-checks"]
"cargo-show-asm 0.2.19 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-asm"]
"cargo-tarpaulin 0.26.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tarpaulin"]
"cargo-udeps 0.1.40 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-udeps"]
"cargo-update 13.0.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-vet 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-vet"]
"cargo-workspaces 0.2.44 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-workspaces",
    "cargo-ws",
]
"codevis 0.8.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["codevis"]
"diesel_cli 2.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["diesel"]
"git-ai-commit 0.1.0 (path+file:///home/milomoisson/projects/git-ai-commit)" = ["git-ai-commit"]
"git-cliff 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "git-cliff",
    "git-cliff-completions",
    "git-cliff-mangen",
]
"git-leave 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-leave"]
"gpg-tui 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "gpg-tui",
    "gpg-tui-completions",
]
"grc 1.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["grc"]
"grcov 0.8.18 (registry+https://github.com/rust-lang/crates.io-index)" = ["grcov"]
"joshuto 0.9.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["joshuto"]
"pgpaste-cli 0.0.0 (path+file:///home/milomoisson/Documents/Developement/Personal/pgpaste/pgpaste-cli)" = ["pgpaste"]
"probe-run 0.3.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["probe-run"]
"qrscan 0.1.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["qrscan"]
"runst 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["runst"]
"rustfilt 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustfilt"]
"sequoia-sq 0.31.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sq"]
"sfz 0.7.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["sfz"]
"songrec 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["songrec"]
"spacedisplay 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["spacedisplay"]
"swp 1.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["swp"]
"tealdeer 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"termimage 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["termimage"]
"thokr 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["thokr"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"tokio-console 0.1.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokio-console"]
"topgrade 12.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["topgrade"]
"wasm-pack 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-pack"]
"cargo-llvm-cov 0.5.23 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-llvm-cov"]
"gping 1.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["gping"]
"grass 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["grass"]
"trunk 0.17.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
