{ self, config, lib, ... }:

let
  inherit (self.outputs) nixosModules;
in
{
  imports = [
    # Patches ACPI tables to fix sound issue
    nixosModules.hardware.asus.zenbook.ux3402za.sound
  ];

  config = {
    local.screen = {
      width = 2880;
      height = 1800;
      scale = 2;
    };

    system.stateVersion = "23.05";

    # --- Generated by `nixos-generate-config` ---
    boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "sdhci_pci" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    # Replaces `<modules>/installer/scan/not-detected.nix` import
    hardware.enableRedistributableFirmware = lib.mkDefault true;
  };
}
