{ config
, lib
, pkgs
, ...
}:

let
  patched-systemd = pkgs.systemd.overrideAttrs (oldAttrs: {
    patches = (oldAttrs.patches or [ ]) ++ [
      # Applying patches to systemd-boot that do not change the version require
      # to remove the previously installed bootloader at /boot/EFI/systemd/systemd-bootx64.efi
      ./systemd-boot-ignore-meta-key.patch
    ];
  });
in
{
  imports = [ ];

  config = {
    system.stateVersion = "23.05";

    systemd.package = patched-systemd;

    # Disable the meta key at the kernel level, rebind unused right alt to meta
    services.udev.extraHwdb = ''
      evdev:atkbd:dmi:bvn*:bvr*:bd*:sv*:pn*:pvr*
       KEYBOARD_KEY_db=reserved
       KEYBOARD_KEY_b8=leftmeta
    '';

    # --- Generated by `nixos-generate-config` ---
    boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "sdhci_pci" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    # Replaces `<modules>/installer/scan/not-detected.nix` import
    hardware.enableRedistributableFirmware = lib.mkDefault true;
  };
}
