{
  lib,

  modulesPath,
  ...
}:

{
  imports = [ "${modulesPath}/profiles/qemu-guest.nix" ];

  config = {
    system.stateVersion = "24.11";

    # --- Generated by `nixos-generate-config` ---
    boot.initrd.availableKernelModules = [
      "xhci_pci"
      "virtio_scsi"
      "sr_mod"
    ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ ];
    boot.extraModulePackages = [ ];

    networking.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
  };
}
