tap "apparition47/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "teamookla/speedtest"
tap "thoughtbot/formulae"
brew "python@3.9", link: false
brew "bat"
brew "cairo"
brew "circleci"
brew "cmatrix"
brew "exa"
brew "fish"
brew "gh"
brew "git"
brew "git-secret"
brew "harfbuzz"
brew "gtk+3"
brew "inetutils", link: false
brew "ncdu"
brew "node"
brew "smimesign"
brew "starship"
brew "telnet", link: false
brew "tldr"
brew "upx"
brew "yarn"
brew "teamookla/speedtest/speedtest"
cask "bitwarden"
cask "diffmerge"
cask "font-fira-code"
cask "mailtrackerblocker"
cask "qlmarkdown"
cask "webpquicklook"
