tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "thoughtbot/formulae"
brew "python@3.9", link: false
brew "bat"
brew "cairo"
brew "circleci"
brew "exa"
brew "fish"
brew "gh"
brew "git"
brew "git-secret"
brew "harfbuzz"
brew "gtk+3"
brew "inetutils", link: false
brew "ncdu"
brew "node"
brew "smimesign"
brew "starship"
brew "telnet"
brew "tldr"
cask "diffmerge"
cask "webpquicklook"
cask "font-fira-code"
