[v1]
"cargo-edit 0.9.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-expand 1.0.27 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-udeps 0.1.29 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-udeps"]
"cargo-update 8.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-workspaces 0.2.34 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-workspaces",
    "cargo-ws",
]
"diesel_cli 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["diesel"]
"git-leave 1.5.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-leave"]
"gping 1.3.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["gping"]
"grc 1.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["grc"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"swp 1.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["swp"]
"termimage 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["termimage"]
"thokr 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["thokr"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"topgrade 9.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["topgrade"]
"wasm-pack 0.10.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-pack"]
