[v1]
"cargo-edit 0.11.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-expand 1.0.31 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-quickinstall 0.2.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-quickinstall"]
"cargo-udeps 0.1.33 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-udeps"]
"cargo-update 10.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-workspaces 0.2.35 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-workspaces",
    "cargo-ws",
]
"diesel_cli 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["diesel"]
"git-leave 1.5.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-leave"]
"gping 1.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["gping"]
"grc 1.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["grc"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"swp 1.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["swp"]
"termimage 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["termimage"]
"thokr 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["thokr"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"tokio-console 0.1.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokio-console"]
"topgrade 9.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["topgrade"]
"wasm-pack 0.10.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-pack"]
