- defaults:
    link:
      relink: true
      create: true
    shell:
      stdout: true
      stderr: true

- clean: ['~']

- link:
    ~/.config/fish: fish/
    ~/.config/regolith2: regolith/
    ~/.config/dunst/dunstrc: dunstrc.ini
    ~/.config/starship.toml.save: starship.toml
    ~/.config/topgrade.toml: topgrade.toml
    ~/.config/helix/config.toml: helix.toml
    ~/.config/nix/nix.conf: nix.conf

    ~/.cargo/.crates.toml: cargo/crates.toml
    ~/.cargo/config.toml: cargo/config.toml

    ~/.profile: profile.sh
    ~/.gitconfig:
    ~/.ssh/config: ssh_config
    ~/.local/share/pnpm/global/5/package.json: pnpm.json
    ~/.prettierrc.json:

- shell:
    - description: Check for brew installation
      command: ./scripts/check_brew.sh

    - description: Install new dependencies
      command: brew bundle

    - description: Check for cargo installation
      command: type rustup && type cargo

    - description: Check for logid symlink
      command: diff logid.cfg /etc/logid.cfg

    - description: Update cargo dependencies and install new ones
      command: cargo install-update --all && ./scripts/rust_deps_update.sh
