- defaults:
    link:
      relink: true
      create: true
    shell:
      stdout: true
      stderr: true

- clean: ['~', '~/.config']

- link:
    ~/.config/fish: fish/
    ~/.config/regolith2: regolith/
    ~/.config/dunst/dunstrc: dunstrc.ini
    ~/.config/starship.toml.save: starship.toml
    ~/.config/topgrade.toml: topgrade.toml
    ~/.config/helix/config.toml: helix.toml
    ~/.config/nix/nix.conf: nix.conf

    ~/.cargo/.crates.toml: cargo/crates.toml
    ~/.cargo/config.toml: cargo/config.toml

    ~/.profile: profile.sh
    ~/.gitconfig:
    ~/.ssh/config: ssh_config
    ~/.local/share/pnpm/global/5/package.json: pnpm.json
    ~/.prettierrc.json:

- shell:
    - description: Install new dependencies if brew is installed
      command: type brew && brew bundle; true
      # Install with `bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

    - description: Check for rustup installation
      command: type rustup
      # Install with `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

    - description: Check for logid symlink
      command: diff logid.cfg /etc/logid.cfg
      # Install `logid` package
