- defaults:
    link:
      relink: true
      create: true
    shell:
      stdout: true
      stderr: true

- clean: ['~']

- link:
    # Yarn stuff
    ~/.yarnrc: yarn/yarnrc
    ~/.config/yarn/global/package.json: yarn/globalDependencies.json
    ~/.config/yarn/global/yarn.lock: yarn/globalDependencies.lock

    # Terminal stuff
    ~/.config/starship.toml.save: starship.toml
    ~/.ssh/config: ssh_config
    ~/.profile: profile.sh
    ~/.cargo/.crates.toml:
    #   ~/fish: .config/fish (disable this as DotBot doesn't support directories)
    #   ^^^^ see the shell part for this verification

    ~/.gitconfig:
    ~/.czrc: czrc.json
    ~/.prettierrc.json:

- shell:
    - description: Check for brew installation
      command: ./scripts/check_brew.sh

    - description: Install new dependencies. Update and upgrade dependencies.
      command: brew bundle && brew update && brew upgrade

    - description: Verify if fish config folder is symlinked
      command: test -L ~/.config/fish

    - description: Check for cargo installation
      command: type rustup && type cargo

    - description: Update cargo dependencies and install new ones
      command: cargo install-update --all && ./scripts/rust_deps_update.sh

    - description: Upgrade yarn packages
      command: yarn global list && yarn global upgrade --latest
