- defaults:
    link:
      relink: true
      create: true
    shell:
      stderr: true

- clean: ['~']

- link:
    # Yarn stuff
    ~/.yarnrc: yarn/yarnrc
    ~/.config/yarn/global/package.json: yarn/globalDependencies.json
    ~/.config/yarn/global/yarn.lock: yarn/globalDependencies.lock

    # Terminal stuff
    ~/.config/starship.toml.save: starship.toml
    ~/.ssh/config: ssh_config
    ~/.profile: profile.sh
    ~/.cargo/.crates.toml:
    #   ~/fish: .config/fish (disable this as DotBot doesn't support directories)

    ~/.gitconfig:
    ~/.czrc: czrc.json
    ~/.prettierrc.json:

- shell:
    - description: Update and upgrade Brew
      command: ./scripts/check_brew.sh && brew bundle && brew update && brew upgrade

    - description: Verify fish symlink
      command: test -L ~/.config/fish

    - description: Verify cargo installation
      command: type rustup && type cargo

    - description: Update cargo dependencies
      command: ./scripts/rust_deps_update.sh

    - description: Upgrade yarn packages
      command: yarn global list && yarn global upgrade --latest
