[misc]
skip_notify = true

# Don't ask for confirmations
assume_yes = true

# Disable specific steps
disable = ["gnome_shell_extensions", "rustup"]

# ignore_failures = ["powershell"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Run `sudo -v` to cache credentials at the start of the run; this avoids a
# blocking password prompt in the middle of a possibly-unattended run.
pre_sudo = true
display_time = true
cleanup = true

[git]
repos = ["~/Documents/Developement/*/*", "~/.config/dotfiles"]

[pre_commands]
# "Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

[firmware]
# Offer to update firmware; if false just check for and display available updates
# upgrade = true
