name: Nix
on:
  - push
  - pull_request

jobs:
  build:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check flake structure
        run: nix flake check
